# Generated by Django 2.0.8 on 2020-09-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FOOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.IntegerField()),
                ('weekly', models.IntegerField()),
                ('monthly', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='profit',
            name='restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swan_app.Restaurants'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swan_app.Restaurants'),
        ),
    ]
